from __future__ import annotations

from typing import Any

class Skprocess: ...
Process = Skprocess
class Pool: ...
class Share: ...
class ProcessTimers: ...

class ProcessError(Exception): ...
class PreRunError(ProcessError): ...
class RunError(ProcessError): ...
class PostRunError(ProcessError): ...
class OnFinishError(ProcessError): ...
class ResultError(ProcessError): ...
class ErrorHandlerError(ProcessError): ...
class ProcessTimeoutError(ProcessError): ...
class ResultTimeoutError(ProcessError): ...

__all__: list[str]
