from __future__ import annotations

from typing import Any

class Skclass: ...
class Skfunction: ...
def sk(*args: Any, **kwargs: Any) -> Any: ...

class SkModifierError(Exception): ...
class FunctionTimeoutError(Exception): ...

__all__: list[str]
