{
  "path": "/Users/ctaro/Suitkaise",
  "level": "TOP",
  "auto_sync": true,
  "multiprocessing_available": false,
  "current_process_id": "63551",
  "created_at": 1750277471.5009542,
  "last_saved": 1750277471.5009542,
  "storage": {
    "local_data": {},
    "cross_process_data": {}
  },
  "cross_process_storage": {},
  "statistics": {
    "reads": 0,
    "writes": 18,
    "errors": 0,
    "cache_hits": 0,
    "cache_misses": 0
  }
}