{
  "path": "/Users/ctaro/Suitkaise/temp_cross_test1",
  "level": "UNDER",
  "auto_sync": true,
  "multiprocessing_available": false,
  "current_process_id": "95901",
  "created_at": 1748129989.138009,
  "last_saved": 1748129989.138009,
  "storage": {
    "local_data": {
      "cross_test": {
        "value": "cross_storage_value",
        "_stored_by_process": "95901",
        "_stored_at": 1748129989.137581,
        "_storage_path": "/Users/ctaro/Suitkaise/temp_cross_test1"
      }
    },
    "cross_process_data": {}
  },
  "cross_process_storage": {}
}